const COLORS = {
    DEFAULT_TEXT_COLOR: '#333',
    PRIMARY: '#090041',
    BACKGROUND: '#FBFBFF',
    PRIMARY_VARIATY: '#6563FF',
    WHITE: 'white',
    SECONDARY_VARIATY: '#EBEBF2',
    BLACK: 'black',
    INPUT_BORDER_COLOR: '#282828'
};

export { COLORS };
