module.exports = {
  preset: 'react-native',
  transform: {
    '^.+\\.(ts|tsx)$': 'babel-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
  testRegex: '(/tests/.*|(\\.|/)(test|spec))\\.(ts|tsx)?$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json', 'node'],
  setupFiles: ['./jest.setup.js'],
  setupFilesAfterEnv: ['<rootDir>/tests/setupTests.ts'],
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.{ts,tsx}'],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 82,
      lines: 88,
      statements: 86,
    },
  },
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/out/',
    '<rootDir>/tests/setupTests.ts',
    '<rootDir>/tests/builders/',
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?|react-native-safe-area-context)/)',
    'node_modules/(?!(@react-native|react-native|@react-navigation|form-data)/)',
  ],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/out/',
    '<rootDir>/tests/setupTests.ts',
    '<rootDir>/tests/builders/',
  ],
  testTimeout: 30000,
  moduleNameMapper: {
    '^react-native-config$': '<rootDir>/tests/__mocks__/react-native-config.js',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
  },
};
