name: Merge to Develop
on:
    pull_request:
      types:
        - closed  
jobs:
  merge-from-develop:
    name: Merge from develop
    runs-on: ubuntu-latest
    steps:
    - name: Merge ${{ github.ref }} -> develop
      if: success() && github.event.pull_request.merged == true && github.base_ref == 'develop' && (github.head_ref == 'feature/*' || github.head_ref == 'hotfix/*' || github.head_ref == 'release/*' || github.head_ref == 'bugfix/*')
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}