name: Merge to Develop
on:
    pull_request:
      types:
        - closed  
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install yarn
        run: npm install -g yarn
      
      - name: Install dependencies
        run: |
          cd AbcallApp
          npm install

      - name: Testing 🧪 with coverage 📊
        run: |
          npm run test:coverage
          
  merge-from-develop:
    name: Merge from develop
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Merge ${{ github.ref }} -> develop
      if: success() && github.event.pull_request.merged == true && github.base_ref == 'develop' && (github.head_ref == 'feature/*' || github.head_ref == 'hotfix/*' || github.head_ref == 'release/*' || github.head_ref == 'bugfix/*')
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}