name: Release
on:
    pull_request:
      types:
        - closed
jobs:
  android-build:
    name: androidBuild
    if: success() && github.event.pull_request.merged == true && github.head_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install yarn
        run: npm install -g yarn
      
      - name: Install dependencies
        run: |
          cd AbcallApp
          npm install
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
    
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools-version: 31.0.0
          ndk: '22.1.7171670'



      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleRelease
        working-directory: AbcallApp

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Validate results with errors
        if: ${{ failure() }}
        env:
          ERROR_MESSAGE: One or various build failed 🔴
        run: echo "::set-output name=answer::${ERROR_MESSAGE}"
      - name: Validate result without errors
        if: ${{ success() }}
        env:
          MESSAGE_SUCCESS: All build were success
        run: echo "::set-output name=answer::${MESSAGE_SUCCESS}"

  ios-build:
    name: iosBuild
    if: success() && github.event.pull_request.merged == true && github.head_ref == 'develop'
    needs: android-build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install yarn
        run: npm install -g yarn
      
      - name: Install dependencies
        run: |
          cd AbcallApp
          npm install
      
      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install
        working-directory: AbcallApp

      - name: Build iOS app
        run: xcodebuild -workspace ios/AbcallApp.xcworkspace -scheme AbcallApp -sdk iphoneos -configuration Release -allowProvisioningUpdates

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app-release.ipa
          path: ios/build/Release-iphoneos/AbcallApp.ipa